export const stories = {
  208: [
    { id: 567, ord: 1, storyid: 208, text: "Der Fuchs und die kleine Eidechse. Eine Fabel der Indianer.", characterid: 425 },
    { id: 568, ord: 2, storyid: 208, text: "Einmal kletterte eine kleine Eidechse an einer Sonnenblume hinauf.", characterid: 426 },
    { id: 569, ord: 3, storyid: 208, text: "Als sie fast oben war, erblickte sie ganz in der Nähe einen streunenden Fuchs. ", characterid: 425 },
    { id: 570, ord: 4, storyid: 208, text: "Was tue ich jetzt nur? Der nächste Unterschlupf ist viel zu weit weg. Bevor ich dort bin, hat mich der Fuchs erwischt. ", characterid: 427 },
    { id: 571, ord: 5, storyid: 208, text: "Ich werde mich tot stellen. Vielleicht übersieht er mich dann. ", characterid: 427 },
    { id: 572, ord: 6, storyid: 208, text: "Die kleine Eidechse stellte sich tot. Aber das half nichts. Der Fuchs hatte sie schon entdeckt. ", characterid: 426 },
    { id: 573, ord: 7, storyid: 208, text: "Füchse können hoch springen. Ich muss mir was einfallen lassen, sonst ist es aus mit mir. ", characterid: 427 },
    { id: 574, ord: 8, storyid: 208, text: "Mmmh. Eidechsen sind zwar nur kleine Happen, aber schmecken trotzdem gut.", characterid: 428 },
    { id: 575, ord: 9, storyid: 208, text: "Und er setzte zum Sprung an.", characterid: 425 },
    { id: 576, ord: 10, storyid: 208, text: "Lass das lieber! Spring ja nicht nach mir! Willst du, dass der Himmel auf die Erde herunterfällt? ", characterid: 427 },
    { id: 577, ord: 11, storyid: 208, text: "Was hast du gesagt?", characterid: 428 },
    { id: 578, ord: 12, storyid: 208, text: "Siehst du nicht, was ich tue? Ich halte den Himmel fest. Oh, was für eine schwere Aufgabe ist das!", characterid: 427 },
    { id: 579, ord: 13, storyid: 208, text: "Ich bin schon ganz erschöpft. Schau bitte und sag mir, ob der Himmel noch dort ist, wo er sein soll. ", characterid: 427 },
    { id: 580, ord: 14, storyid: 208, text: "Es war um die Mittagszeit.", characterid: 425 },
    { id: 581, ord: 15, storyid: 208, text: "Die Sonne schien.", characterid: 426 },
    { id: 582, ord: 16, storyid: 208, text: "Ein leichter Wind wehte.", characterid: 425 },
    { id: 583, ord: 17, storyid: 208, text: "Weiße Sommerwolken segelten über den Himmel.", characterid: 426 },
    { id: 584, ord: 18, storyid: 208, text: "Der Fuchs blickte hoch und schaute und schaute.", characterid: 425 },
    { id: 585, ord: 19, storyid: 208, text: "Das Sonnenlicht blendete ihn.", characterid: 426 },
    { id: 586, ord: 20, storyid: 208, text: "Ich kann nicht mehr. Aber ich darf nicht aufgeben. Senkt der Himmel sich schon herab? ", characterid: 427 },
    { id: 587, ord: 21, storyid: 208, text: "Der Himmel schien auf einmal viel niedriger zu sein. Dem Fuchs war, als senkten die Wolken sich tiefer. ", characterid: 425 },
    { id: 588, ord: 22, storyid: 208, text: "Am besten ist es, wenn ich die Eidechse in Ruhe lasse. Womöglich fällt uns sonst der Himmel auf den Kopf. ", characterid: 428 },
    { id: 589, ord: 23, storyid: 208, text: "Der Fuchs trottete davon.", characterid: 425 },
    { id: 590, ord: 24, storyid: 208, text: "Puh. Nochmal Glück gehabt.", characterid: 427 },
    { id: 591, ord: 25, storyid: 208, text: "Von Zeit zu Zeit warf der Fuchs ängstliche Blicke zum Himmel hinauf.", characterid: 426 },
    { id: 592, ord: 26, storyid: 208, text: "Nichts geschah!", characterid: 425 },
    { id: 593, ord: 27, storyid: 208, text: "Die Sonne schien.", characterid: 426 },
    { id: 594, ord: 28, storyid: 208, text: "Weiße Sommerwolken segelten hoch über der Erde.", characterid: 425 },
    { id: 595, ord: 29, storyid: 208, text: "Kann das sein? Eine kleine Eidechse hält den Himmel fest? Das gibt es doch nicht.", characterid: 428 },
    { id: 596, ord: 30, storyid: 208, text: "Der Fuchs kehrte um und lief zur Sonnenblume zurück.", characterid: 426 },
    { id: 597, ord: 31, storyid: 208, text: "Die kleine Eidechse war nicht mehr oben am Stängel.", characterid: 425 },
    { id: 598, ord: 32, storyid: 208, text: "Sie war längst geflohen und hatte sich ein sicheres Versteck gesucht.", characterid: 426 },
    { id: 599, ord: 33, storyid: 208, text: "Die Eidechse hat mich hereingelegt! Recht geschieht mir!", characterid: 428 },
    { id: 600, ord: 34, storyid: 208, text: "Er hätte doch gleich merken müssen, dass es ein Schwindel ist.", characterid: 425 },
    { id: 601, ord: 35, storyid: 208, text: "Das wird ihm eine Lehre sein:", characterid: 426 },
    { id: 602, ord: 36, storyid: 208, text: "Glaube nicht alles, was dir einer erzählt. Denke zuerst darüber nach, ob es auch wahr sein kann. ", characterid: 428 },
  ],
  210: [
    { id: 619, ord: 1, storyid: 210, text: "In einem dichten, undurchdringlichen Wald, lebte die Eule Elara.", characterid: 433 },
    { id: 620, ord: 2, storyid: 210, text: "Sie war berühmt für ihre Weisheit und ihr außergewöhnliches Urteilsvermögen. Jedes Tier, das ein Problem hatte, suchte ihren Rat.", characterid: 433 },
    { id: 621, ord: 3, storyid: 210, text: "Eines Tages begegnete ihr der Fuchs Felix. Felix war nicht nur stolz, sondern auch arrogant.", characterid: 433 },
    { id: 622, ord: 4, storyid: 210, text: "Ich bin das gewiefteste Tier im ganzen Wald!", characterid: 434 },
    { id: 623, ord: 5, storyid: 210, text: "Felix prahlte überheblich. Elara sah ihn mit ruhigen Augen an.", characterid: 433 },
    { id: 624, ord: 6, storyid: 210, text: "Hochmut führt oft zu einem Desaster.", characterid: 435 },
    { id: 625, ord: 7, storyid: 210, text: "Das sagte die Eule bedächtig. Felix schnaubte daraufhin.", characterid: 433 },
    { id: 626, ord: 8, storyid: 210, text: "Ach, ich brauche keinen Rat. Mir ist noch nie etwas passiert!", characterid: 434 },
    { id: 627, ord: 9, storyid: 210, text: "Sagtest du das nicht auch gestern, als du dachtest, du könntest über den Fluss springen?", characterid: 435 },
    { id: 628, ord: 10, storyid: 210, text: "Elara fragte das sanft. Felix schaute verlegen zur Seite.", characterid: 433 },
    { id: 629, ord: 11, storyid: 210, text: "Das… war anders.", characterid: 434 },
    { id: 630, ord: 12, storyid: 210, text: "Elara lächelt nur wissend.", characterid: 433 },
    { id: 631, ord: 13, storyid: 210, text: "Plötzlich ertönte ein lautes Rascheln. Ein kleiner Hase war in eine komplizierte Konstruktion geraten!", characterid: 433 },
    { id: 632, ord: 14, storyid: 210, text: "Felix sprang los, aber er scheiterte kläglich. Er versuchte es vergeblich und wurde immer frustrierter.", characterid: 433 },
    { id: 633, ord: 15, storyid: 210, text: "Elara flog hinüber, untersuchte die Falle und befreite den Hasen mit einem geschickten Schwung.", characterid: 433 },
    { id: 634, ord: 16, storyid: 210, text: "Siehst du, Felix, manchmal ist Voraussicht wichtiger als Geschwindigkeit.", characterid: 435 },
    { id: 635, ord: 17, storyid: 210, text: "Felix senkte den Kopf. Von diesem Tag an lernte er, nicht nur stolz zu sein, sondern auch beharrlich, umsichtig und reflektiert zu handeln.", characterid: 433 },
    { id: 636, ord: 18, storyid: 210, text: "So wurden die Eule und der Fuchs gute Freunde, die gemeinsam jedes Problem lösen konnten.", characterid: 433 },
  ],
};
